- name: Waka - Readme
  uses: athul/waka-readme@0.1.2
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: # default is ${{ github.token }}
    # Your Wakatime API Key
    WAKATIME_API_KEY: 645fe7fb-8780-4862-bd97-5ea2e83289bc
    # Your GitHub username
    USERNAME: Kyomotoi# optional, default is ${{ github.repository_owner }}
